name: Publish Docker Hub Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

env:
  DOCKERHUB_USERNAME: basiliskdev
  IMAGE_NAME: loong64-openeuler-uxp-build-environment
  IMAGE_PLATFORM: linux/loong64

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: loong64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Generate Docker metadata
        id: metas
        uses: docker/metadata-action@v6
        with:
          images: docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.IMAGE_PLATFORM }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
